# Ruby CircleCI 2.1 configuration file
version: 2.1
jobs:
  test_and_tag:
    docker:
       - image: circleci/ruby:2.6.6-node-browsers
         environment:
           DATABASE_URL: postgresql://localhost/nsw_procure_test

       - image: circleci/postgres:10.6-alpine-ram
         environment:
           POSTGRES_USER: circleci
           POSTGRES_DB: nsw_procure_test

    working_directory: ~/repo

    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - "*"
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bin/setup
      - run:
          name: run tests
          command: |
            bundle exec rails test
      - run:
          name: tag successful build
          command: |
            git config --global user.name "CircleCI tagging robot"
            export TAG=v$CIRCLE_BUILD_NUM
            git tag -a $TAG -m 'adding version tag'
            git push origin $TAG

workflows:
  version: 2.1
  test_and_tag:
    jobs:
      - test_and_tag
